import { Inter } from "next/font/google";
import "./globals.css";

// Configuración de la fuente
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



// Componente RootLayout, definido una sola vez
export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${inter.className} h-[100dvh] flex flex-col`}>{children}</body>
    </html>
  );
}
